config/routes.rb
Taskio::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }
  get '/awaiting_confirmation',
    :to => "users#confirmation",
    :as => 'confirm_user'

  root :to => "dashboards#show"
  resource :dashboard, :only => 'show'
  resources :tasks do
    resources :subtasks
  end
  resources :groups do
    resources :tasks
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible  :name
  validates :name, :presence => true
  has_many :membership
  has_many :users, through: :membership
  has_many :tasks
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  attr_accessible :user_id, :group_id
  belongs_to :user
  belongs_to :group
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
  belongs_to :task
  attr_accessible :created_at, :description, :priority, :title
  validates :title, presence: true

  def priority_string
    if :priority == 1
      "High"
    elsif :priority == 2
      "Medium"
    else
      "Low"
    end
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :created_at, :description, :priority,
                  :title
  validates :title, presence: true

  has_many :subtasks

  belongs_to :group

  def priority_string
    if :priority == 1
      "High"
    elsif :priority == 2
      "Medium"
    else
      "Low"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :memberships
  has_many :groups, :through => :memberships
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_membership

  def show

  end

  private

  def find_membership
    @membership = Membership.where(user_id: current_user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :find_membership

  # def index
  #   @groups = Group.find(@membership.group_id)
  # end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])

    if @group.save
      @membership = Membership.create(user_id: current_user.id, group_id: @group.id)
      redirect_to dashboard_path, :notice => "Your group has been created."
    else
      flash[:alert] = "Group has not been created."
      render "new"
    end
  end

  private

  def find_membership
    @membership = Membership.where(user_id: current_user.id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def after_inactive_sign_up_path_for(resource)
    confirm_user_path
  end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_task
  before_filter :find_subtask, :only => [:show, :edit, :update, :destroy]

  def new
    @subtask = @task.subtasks.build
  end

  def create
    @subtask = @task.subtasks.build(params[:subtask])
    # @subtask.user = current_user
    if @subtask.save
      flash[:notice] = "Subtask has been created."
      redirect_to tasks_path
    else
      flash[:alert] = "Subtask has not been created."
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @subtask.update_attributes(params[:subtask])
      flash[:notice] = "Subtask has been updated."
      redirect_to [@task, @subtask]
    else
      flash[:alert] = "Subtask has not been updated."
      render :action => :edit
    end
  end

  def destroy
    @subtask.destroy
    flash[:notice] = "Your subtask has been deleted."
    redirect_to tasks_path
  end

private
  def find_task
    @task = Task.find(params[:task_id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The task you were looking " +
                "for could not be found."
    redirect_to root_path
  end

  def find_subtask
    @subtask = @task.subtasks.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :authenticate_user!

  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Your task has been created.' }
      else
        flash[:alert] = "Your task was not created."
        format.html { render action: "new" }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Your task has been updated.' }
      else
        flash[:alert] = "Your task was not updated."
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, alert: 'Your task has been deleted.' }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def confirmation

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def nested_tasks(tasks)
    tasks.map do |task, subtasks|
      render(task) + content_tag(:div, nested_tasks(subtasks), :class => "nested_tasks")
    end.join.html_safe
  end
end

app/views/dashboards/show.html.erb
<h3> Welcome, <%= current_user.email %></h3>
<h2>Check out your groups!</h2>
<%= render partial: "groups/group_list" %>

<%= link_to "Create Group", new_group_path %>

app/views/groups/_group_list.html.erb
<ul id='group_list'>
  <% @membership.each do |membership| %>
    <% @group = Group.find(membership.group_id) %>
      <li id="<%= @group.name %>"><%= link_to @group.name, @group %>
  <% end %>
</ul>

app/views/groups/index.html.erb
<h2>Check out your groups!</h2>
<ul id='group_list'>
  <% @membership.each do |membership| %>
    <% @group = Group.find(membership.group_id) %>
    <li id="<%= @group.name %>"><%= link_to @group.name, @group %>
  <% end %>
</ul>

<%= link_to "Create Group", new_group_path %>

app/views/groups/new.html.erb
<h1>New Task List</h1>

<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', dashboard_path %>

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <div class="container">
      <% if user_signed_in? %>
          Signed in as <%= current_user.email %>
      <% end %>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class ="navbar-inner">
    <div class="container">
      <%= link_to "Taskio", '#', id: "main_title" %>
       <nav>
        <ul class="nav pull-right">
      <% if user_signed_in? %>
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <li><%= link_to "Invite User", new_user_invitation_path %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
  <div class="container">

    <% flash.each do |key, value| %>
      <div class='flash' id='<% key %>'>
        <%= value %>
      </div>
    <% end %>
 <%= yield %>

    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/subtasks/_form.html.erb
<%= form_for [@task, @subtask] do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.select(:priority, [["High", 1], ["Medium", 2], ["Low", 3]]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subtasks/edit.html.erb
<h2>Edit Subtask</h2>

<%= render "form" %>

app/views/subtasks/new.html.erb
<h1>New Subtask</h1>

<%= render "form" %>

app/views/subtasks/show.html.erb
<ul id='subtask'>
    <h2><%= @subtask.title %></h2>
  <li>
    <b>Description:</b>
    <%= @subtask.description %>
  </li>
  <li>
    <b>Priority:</b>
    <%= @subtask.priority_string %>
  </li>
  <div class="actions">
    <%= link_to 'Edit', edit_task_subtask_path %> |
    <%= link_to 'Delete', [@task, @subtask],
          method: :delete,
          confirm: "Are you sure you want to delete this subtask?" %> |
    <%= link_to 'Back', @subtask.task %>
  </div>
</ul>

app/views/task_lists/new.html.erb
<h1>New Task List</h1>

<%= form_for(@task_list) do |f| %>
  <% if @task_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

      <ul>
      <% @task_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', dashboard_path %>

app/views/tasks/_form.html.erb
<%= form_for([@task_list, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :created_at %><br />
    <%= f.datetime_select :created_at %>
  </div>
  <%= f.hidden_field :parent_id, :value => params[:parent_id] if params[:parent_id] %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr>
  <td><%= link_to task.title, task_list_task_path(@task_list, task) %></td>
  <td><%= task.description %></td>
  <td><%= task.priority %></td>
  <td><%= task.created_at %></td>
  <td><%= link_to 'Subtask', new_task_list_task_path(@task_list, :parent_id => task) %></td>
  <td><%= link_to 'Edit', edit_task_list_task_path(@task_list, task) %></td>
  <td><%= link_to 'Destroy', task_list_task_path(@task_list, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', task_list_task_path(@task_list, @task) %> |
<%= link_to 'Back', task_list_tasks_path(@task_list) %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Priority</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%= nested_tasks @tasks.arrange(:order => :created_at) %>

</table>

<br />

<%= link_to 'New Task', new_task_list_task_path(@task_list) %>

app/views/tasks/new.html.erb
<h1>Create Task</h1>

<%= render @task.parent if @task.parent %>

<%= render 'form' %>

<%= link_to "Back", task_list_tasks_path(@task_list) %>

app/views/tasks/show.html.erb
<p id="notice"> </p>
<ul id='task'>
    <h2><%= @task.title %></h2>
  <li>
    <b>Description:</b>
    <%= @task.description %>
  </li>
  <li>
    <b>Priority:</b>
    <%= @task.priority_string %>
  </li>
  <div class="actions">
    <%= link_to 'Create Subtask', new_task_subtask_path(@task) %> |
    <%= link_to 'Edit', edit_task_path(@task) %> |
    <%= link_to 'Delete', task_path(@task),
          method: :delete,
          confirm: "Are you sure you want to delete this task?" %> |
    <%= link_to 'Back', tasks_path %>

  </div>
    <ul id-'subtask'>
      <% @task.subtasks.each do |subtask| %>
          <h4><%= link_to subtask.title, [@task, subtask] %></h4>
        <li><b>Description: </b><%= subtask.description %></li>
        <li><b>Priority: </b><%= subtask.priority_string %></li>
      </br>
      <div class="actions">
    <%= link_to 'Edit', edit_task_subtask_path(@task, subtask) %> |
    <%= link_to 'Delete', [@task, subtask],
          method: :delete,
          confirm: "Are you sure you want to delete this subtask?" %>
  </div>
      <% end %>
    </ul>
</ul>

app/views/users/confirmation.html.erb
<h1>You have signed up successfully.</h1>

Please confirm your account before signing in.

app/views/users/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>